version: "3.9"
services:
  db:
    image: postgres:17 
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vetclinic2
    ports:
      - "5432:5432"
    volumes:
      - ./db/data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend 
    container_name: backend_container
    environment:
      FLASK_APP: manage.py
      FLASK_ENV: development
    depends_on:
      - db  
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./frontend 
    container_name: frontend_container
    depends_on:
      - backend
    ports:
      - "3000:3000"
