[versions]
agp = "8.8.0"
json = "20210307"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.6.1"
material = "1.12.0"
materialCalendarview = "2.0.1"
okhttp = "4.9.0"
volley = "1.2.1"

[libraries]
json = { module = "org.json:json", version.ref = "json" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
material-calendarview = { module = "com.prolificinteractive:material-calendarview", version = "1.4.3" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
volley = { module = "com.android.volley:volley", version.ref = "volley" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

